// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250810104257_INtiProduct")]
    partial class INtiProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Music"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<double>("price100")
                        .HasColumnType("float");

                    b.Property<double>("price50")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jon Skeet",
                            Description = "Advanced guide to C# programming.",
                            ISBN = "9781617294532",
                            ListPrice = 59.990000000000002,
                            Name = "C# in Depth",
                            price = 54.990000000000002,
                            price100 = 44.990000000000002,
                            price50 = 49.990000000000002
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Lock",
                            Description = "Comprehensive guide to building web apps with ASP.NET Core.",
                            ISBN = "9781617294617",
                            ListPrice = 64.989999999999995,
                            Name = "ASP.NET Core in Action",
                            price = 59.990000000000002,
                            price100 = 49.990000000000002,
                            price50 = 54.990000000000002
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert C. Martin",
                            Description = "A Handbook of Agile Software Craftsmanship.",
                            ISBN = "9780132350884",
                            ListPrice = 49.990000000000002,
                            Name = "Clean Code",
                            price = 44.990000000000002,
                            price100 = 34.990000000000002,
                            price50 = 39.990000000000002
                        },
                        new
                        {
                            Id = 4,
                            Author = "Erich Gamma et al.",
                            Description = "Elements of Reusable Object-Oriented Software.",
                            ISBN = "9780201633610",
                            ListPrice = 54.990000000000002,
                            Name = "Design Patterns",
                            price = 49.990000000000002,
                            price100 = 39.990000000000002,
                            price50 = 44.990000000000002
                        },
                        new
                        {
                            Id = 5,
                            Author = "Andrew Hunt & David Thomas",
                            Description = "Your Journey to Mastery.",
                            ISBN = "9780135957059",
                            ListPrice = 44.990000000000002,
                            Name = "The Pragmatic Programmer",
                            price = 39.990000000000002,
                            price100 = 29.989999999999998,
                            price50 = 34.990000000000002
                        },
                        new
                        {
                            Id = 6,
                            Author = "Adam Freeman",
                            Description = "Best practices and performance optimization for EF Core.",
                            ISBN = "9781484287486",
                            ListPrice = 69.989999999999995,
                            Name = "Pro Entity Framework Core 7",
                            price = 64.989999999999995,
                            price100 = 54.990000000000002,
                            price50 = 59.990000000000002
                        },
                        new
                        {
                            Id = 7,
                            Author = "Douglas Crockford",
                            Description = "Deep dive into the best features of JavaScript.",
                            ISBN = "9780596517748",
                            ListPrice = 39.990000000000002,
                            Name = "JavaScript: The Good Parts",
                            price = 34.990000000000002,
                            price100 = 24.989999999999998,
                            price50 = 29.989999999999998
                        },
                        new
                        {
                            Id = 8,
                            Author = "Kyle Simpson",
                            Description = "Understanding JavaScript deeply.",
                            ISBN = "9781098124045",
                            ListPrice = 34.990000000000002,
                            Name = "You Don’t Know JS Yet",
                            price = 29.989999999999998,
                            price100 = 19.989999999999998,
                            price50 = 24.989999999999998
                        },
                        new
                        {
                            Id = 9,
                            Author = "Alan Beaulieu",
                            Description = "Master SQL for data management and analysis.",
                            ISBN = "9781492057611",
                            ListPrice = 49.990000000000002,
                            Name = "Learning SQL",
                            price = 44.990000000000002,
                            price100 = 34.990000000000002,
                            price50 = 39.990000000000002
                        },
                        new
                        {
                            Id = 10,
                            Author = "Nigel Poulton",
                            Description = "Comprehensive Docker reference.",
                            ISBN = "9781521822807",
                            ListPrice = 54.990000000000002,
                            Name = "Docker Deep Dive",
                            price = 49.990000000000002,
                            price100 = 39.990000000000002,
                            price50 = 44.990000000000002
                        },
                        new
                        {
                            Id = 11,
                            Author = "Chris Richardson",
                            Description = "With examples in Java and Spring.",
                            ISBN = "9781617294549",
                            ListPrice = 64.989999999999995,
                            Name = "Microservices Patterns",
                            price = 59.990000000000002,
                            price100 = 49.990000000000002,
                            price50 = 54.990000000000002
                        },
                        new
                        {
                            Id = 12,
                            Author = "Eric Freeman",
                            Description = "A brain-friendly guide to design patterns.",
                            ISBN = "9781492078005",
                            ListPrice = 59.990000000000002,
                            Name = "Head First Design Patterns",
                            price = 54.990000000000002,
                            price100 = 44.990000000000002,
                            price50 = 49.990000000000002
                        },
                        new
                        {
                            Id = 13,
                            Author = "Brendan Burns",
                            Description = "Dive into Kubernetes cluster management.",
                            ISBN = "9781492046530",
                            ListPrice = 64.989999999999995,
                            Name = "Kubernetes Up & Running",
                            price = 59.990000000000002,
                            price100 = 49.990000000000002,
                            price50 = 54.990000000000002
                        },
                        new
                        {
                            Id = 14,
                            Author = "Eric Matthes",
                            Description = "A hands-on introduction to programming.",
                            ISBN = "9781593279288",
                            ListPrice = 44.990000000000002,
                            Name = "Python Crash Course",
                            price = 39.990000000000002,
                            price100 = 29.989999999999998,
                            price50 = 34.990000000000002
                        },
                        new
                        {
                            Id = 15,
                            Author = "Luciano Ramalho",
                            Description = "Clear, concise, and effective programming in Python.",
                            ISBN = "9781492056355",
                            ListPrice = 64.989999999999995,
                            Name = "Fluent Python",
                            price = 59.990000000000002,
                            price100 = 49.990000000000002,
                            price50 = 54.990000000000002
                        },
                        new
                        {
                            Id = 16,
                            Author = "Martin Fowler",
                            Description = "Improving the design of existing code.",
                            ISBN = "9780134757599",
                            ListPrice = 69.989999999999995,
                            Name = "Refactoring",
                            price = 64.989999999999995,
                            price100 = 54.990000000000002,
                            price50 = 59.990000000000002
                        },
                        new
                        {
                            Id = 17,
                            Author = "Eric Evans",
                            Description = "Tackling complexity in the heart of software.",
                            ISBN = "9780321125217",
                            ListPrice = 74.989999999999995,
                            Name = "Domain-Driven Design",
                            price = 69.989999999999995,
                            price100 = 59.990000000000002,
                            price50 = 64.989999999999995
                        },
                        new
                        {
                            Id = 18,
                            Author = "Mike Cohn",
                            Description = "Mastering Agile project estimation.",
                            ISBN = "9780131479418",
                            ListPrice = 49.990000000000002,
                            Name = "Agile Estimating and Planning",
                            price = 44.990000000000002,
                            price100 = 34.990000000000002,
                            price50 = 39.990000000000002
                        },
                        new
                        {
                            Id = 19,
                            Author = "Jez Humble",
                            Description = "Reliable software releases through automation.",
                            ISBN = "9780321601919",
                            ListPrice = 64.989999999999995,
                            Name = "Continuous Delivery",
                            price = 59.990000000000002,
                            price100 = 49.990000000000002,
                            price50 = 54.990000000000002
                        },
                        new
                        {
                            Id = 20,
                            Author = "Betsy Beyer",
                            Description = "How Google runs production systems.",
                            ISBN = "9781491929124",
                            ListPrice = 74.989999999999995,
                            Name = "Site Reliability Engineering",
                            price = 69.989999999999995,
                            price100 = 59.990000000000002,
                            price50 = 64.989999999999995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
